# This is a basic workflow to help you get started with Actions

name: Build APK

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M_%S')"
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    # - run: flutter build appbundle
    - uses: actions/upload-artifact@v3
      with:
        path: build/app/outputs/flutter-apk/app-release.apk
        name: water-me-${{ steps.date.outputs.date }}.apk
